src/main/java/com/ces/enade/model/Prova.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ces.enade.model;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author mathe
 */
@Entity
@Table(name = "Prova")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Prova.findAll", query = "SELECT p FROM Prova p"),
    @NamedQuery(name = "Prova.findByIdProva", query = "SELECT p FROM Prova p WHERE p.idProva = :idProva"),
    @NamedQuery(name = "Prova.findByDataProva", query = "SELECT p FROM Prova p WHERE p.dataProva = :dataProva")})
public class Prova implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "idProva")
    private Integer idProva;
    @Basic(optional = false)
    @NotNull
    @Column(name = "dataProva")
    @Temporal(TemporalType.DATE)
    private Date dataProva;
    @JoinTable(name = "Prova_has_Questao", joinColumns = {
        @JoinColumn(name = "Prova_idProva", referencedColumnName = "idProva")}, inverseJoinColumns = {
        @JoinColumn(name = "Questao_idQuestao", referencedColumnName = "idQuestao")})
    @ManyToMany
    private List<Questao> questaoList;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "provaidProva")
    private List<Resultado> resultadoList;

    public Prova() {
    }

    public Prova(Integer idProva) {
        this.idProva = idProva;
    }

    public Prova(Integer idProva, Date dataProva) {
        this.idProva = idProva;
        this.dataProva = dataProva;
    }

    public Integer getIdProva() {
        return idProva;
    }

    public void setIdProva(Integer idProva) {
        this.idProva = idProva;
    }

    public Date getDataProva() {
        return dataProva;
    }

    public void setDataProva(Date dataProva) {
        this.dataProva = dataProva;
    }

    public String getDataFormatada() {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        return df.format(dataProva);
    }

    @XmlTransient
    public List<Questao> getQuestaoList() {
        return questaoList;
    }

    public void setQuestaoList(List<Questao> questaoList) {
        this.questaoList = questaoList;
    }

    @XmlTransient
    public List<Resultado> getResultadoList() {
        return resultadoList;
    }

    public void setResultadoList(List<Resultado> resultadoList) {
        this.resultadoList = resultadoList;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idProva != null ? idProva.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Prova)) {
            return false;
        }
        Prova other = (Prova) object;
        if ((this.idProva == null && other.idProva != null) || (this.idProva != null && !this.idProva.equals(other.idProva))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return idProva.toString();
    }

}

src/main/java/com/ces/enade/controller/GraficoController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ces.enade.controller;

import com.ces.enade.dao.FactoryDAO;
import com.ces.enade.dao.ResultadoDAO;
import com.ces.enade.dao.UsuarioDAO;
import com.ces.enade.model.Resultado;
import com.ces.enade.model.Usuario;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.BarChartModel;
import org.primefaces.model.chart.ChartSeries;
import org.primefaces.model.chart.PieChartModel;

/**
 *
 * @author mathe
 */
@Named
@SessionScoped
public class GraficoController implements Serializable {

    private final FactoryDAO factoryDAO = new FactoryDAO();
    private final Class<ResultadoDAO> daoClassResultado;
    private final Class<UsuarioDAO> daoClassUsuario;

    List<Resultado> ultimosDezResultados = new ArrayList<>();
    List<Resultado> totalResultados = new ArrayList<>();
    List<Usuario> totalAlunos = new ArrayList<>();

    private PieChartModel pieModel;
    private BarChartModel barModel;

    public GraficoController() {
        daoClassResultado = ResultadoDAO.class;
        daoClassUsuario = UsuarioDAO.class;
        ultimosDezResultados = factoryDAO.getInstance(daoClassResultado).findUltimosDezResultados();
        totalResultados = factoryDAO.getInstance(daoClassResultado).findAll();
        totalAlunos = factoryDAO.getInstance(daoClassUsuario).findAllAlunos();
    }

    @PostConstruct
    public void init() {
        createPieModel();
        createBarModel();
    }

    private void createPieModel() {
        pieModel = new PieChartModel();

        double qtdAlunosFizeram = (double) totalResultados.size() / (double) totalAlunos.size() * 100;
        pieModel.set("Fizeram", qtdAlunosFizeram);
        pieModel.set("Não fizeram", 100 - qtdAlunosFizeram);

        pieModel.setTitle("Alunos que fizeram e não fizeram a prova (%)");
        pieModel.setLegendPosition("w");
        pieModel.setShadow(false);
    }

    private void createBarModel() {
        ChartSeries notas = new ChartSeries();
        notas.setLabel("Notas");

        ultimosDezResultados.stream().forEach(it -> notas.set(it.getUsuarioidUsuario().getNome(), it.getValorObtido()));

        BarChartModel model = new BarChartModel();
        model.addSeries(notas);
        barModel = model;

        barModel.setTitle("Notas dos últimos 10 alunos que fizeram a prova");
        barModel.setLegendPosition("ne");

        Axis xAxis = barModel.getAxis(AxisType.X);
        xAxis.setLabel("Alunos");

        Axis yAxis = barModel.getAxis(AxisType.Y);
        yAxis.setLabel("Notas");
        yAxis.setMin(0);
        yAxis.setMax(10);
    }

    public PieChartModel getPieModel() {
        return pieModel;
    }

    public void setPieModel(PieChartModel pieModel) {
        this.pieModel = pieModel;
    }

    public BarChartModel getBarModel() {
        return barModel;
    }

    public void setBarModel(BarChartModel barModel) {
        this.barModel = barModel;
    }

    public List<Resultado> getUltimosDezResultados() {
        return ultimosDezResultados;
    }

    public void setUltimosDezResultados(List<Resultado> ultimosDezResultados) {
        this.ultimosDezResultados = ultimosDezResultados;
    }

    public List<Resultado> getTotalResultados() {
        return totalResultados;
    }

    public void setTotalResultados(List<Resultado> totalResultados) {
        this.totalResultados = totalResultados;
    }

    public List<Usuario> getTotalAlunos() {
        return totalAlunos;
    }

    public void setTotalAlunos(List<Usuario> totalAlunos) {
        this.totalAlunos = totalAlunos;
    }

}

src/main/java/com/ces/enade/controller/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ces.enade.controller;

import com.ces.enade.dao.FactoryDAO;
import com.ces.enade.dao.UsuarioDAO;
import com.ces.enade.model.Usuario;
import com.ces.enade.util.Constants;
import com.ces.enade.util.EncryptUtil;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

/**
 *
 * @author mathe
 */
@Named
@SessionScoped
public class LoginController implements Serializable {

    private final FactoryDAO factoryDAO = new FactoryDAO();
    private final Class<UsuarioDAO> daoClass;

    private final UsuarioController usuarioController;
    private Usuario usuarioLogin;
    private Usuario usuarioCadastro;

    public LoginController() {
        daoClass = UsuarioDAO.class;
        usuarioController = new UsuarioController();
        usuarioLogin = new Usuario();
        usuarioCadastro = new Usuario();
    }

    public String cadastrar() {
        Usuario usuarioFind = factoryDAO.getInstance(daoClass).findByEmail(usuarioCadastro);
        if (usuarioFind == null) {
            Usuario usuarioPersisted = usuarioController.salvarUsuario(usuarioCadastro, false);
            setUsuarioLogin(usuarioPersisted);

            HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
            session.setAttribute(Constants.HTTP_SESSION_ATRIBUTE_LOGADO, usuarioLogin);
            return Constants.URL_INDEX;
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "E-mail já cadastrado. Por favor faça o login!", null));
            return null;
        }
    }

    public String login() {
        usuarioLogin.setSenha(EncryptUtil.encrypt(usuarioLogin.getSenha()));
        Usuario usuarioFind = factoryDAO.getInstance(daoClass).logIn(usuarioLogin);
        if (usuarioFind == null) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "E-mail ou senha inválidos!", null));
            return null;
        } else {
            setUsuarioLogin(usuarioFind);
            HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
            session.setAttribute(Constants.HTTP_SESSION_ATRIBUTE_LOGADO, usuarioLogin);
            return Constants.URL_INDEX;
        }
    }

    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return Constants.URL_LOGIN;
    }

    public String goHome() {
        return Constants.URL_INDEX;
    }

    public boolean isProfessor() {
        return usuarioLogin.getTipoUsuarioidTipoUsuario().getNomeTipoUsuario().equals("Professor");
    }

    public Usuario getUsuarioLogin() {
        return usuarioLogin;
    }

    public void setUsuarioLogin(Usuario usuarioLogin) {
        this.usuarioLogin = usuarioLogin;
    }

    public Usuario getUsuarioCadastro() {
        return usuarioCadastro;
    }

    public void setUsuarioCadastro(Usuario usuarioCadastro) {
        this.usuarioCadastro = usuarioCadastro;
    }

}

src/main/java/com/ces/enade/controller/ProvaController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ces.enade.controller;

import com.ces.enade.dao.FactoryDAO;
import com.ces.enade.dao.ProvaDAO;
import com.ces.enade.model.Prova;
import javax.faces.event.ActionEvent;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import org.primefaces.event.RowEditEvent;

/**
 *
 * @author mathe
 */
@Named
@SessionScoped
public class ProvaController implements Serializable {

    private final FactoryDAO factoryDAO = new FactoryDAO();
    private final Class<ProvaDAO> daoClass;

    Prova prova = new Prova();
    List<Prova> provas = new ArrayList<>();

    public ProvaController() {
        daoClass = ProvaDAO.class;
        provas = factoryDAO.getInstance(daoClass).findAll();
        prova = new Prova();
    }

    public void gravar(ActionEvent actionEvent) {
        factoryDAO.getInstance(daoClass).merge(prova);
        provas = factoryDAO.getInstance(daoClass).findAll();
        prova = new Prova();
    }

    public void remover(ActionEvent actionEvent) {
        factoryDAO.getInstance(daoClass).remove(prova.getIdProva());
        provas = factoryDAO.getInstance(daoClass).findAll();
        prova = new Prova();
    }

    public void onRowEdit(RowEditEvent event) {
        Prova obj = (Prova) event.getObject();
        setProva(obj);
        gravar(null);
        FacesMessage msg = new FacesMessage("Editado", obj.toString());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public void onRowCancel(RowEditEvent<Prova> event) {
        FacesMessage msg = new FacesMessage("Cancelado", event.getObject().toString());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public Prova getProva() {
        return prova;
    }

    public void setProva(Prova prova) {
        this.prova = prova;
    }

    public List<Prova> getProvas() {
        return provas;
    }

    public void setProvas(List<Prova> provas) {
        this.provas = provas;
    }

}

src/main/java/com/ces/enade/controller/QuestaoController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ces.enade.controller;

import com.ces.enade.dao.FactoryDAO;
import com.ces.enade.dao.QuestaoDAO;
import com.ces.enade.model.Questao;
import javax.faces.event.ActionEvent;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import org.primefaces.event.RowEditEvent;

/**
 *
 * @author mathe
 */
@Named
@SessionScoped
public class QuestaoController implements Serializable {

    private final FactoryDAO factoryDAO = new FactoryDAO();
    private final Class<QuestaoDAO> daoClass;

    Questao questao = new Questao();
    List<Questao> questoes = new ArrayList<>();
    List<Questao> questoesAtivas = new ArrayList<>();

    public QuestaoController() {
        daoClass = QuestaoDAO.class;
        questoes = factoryDAO.getInstance(daoClass).findAll();
        questoesAtivas = factoryDAO.getInstance(daoClass).findQuestoesAtivas();
        questao = new Questao();
    }

    public void gravar(ActionEvent actionEvent) {
        factoryDAO.getInstance(daoClass).merge(questao);
        questoes = factoryDAO.getInstance(daoClass).findAll();
        questoesAtivas = factoryDAO.getInstance(daoClass).findQuestoesAtivas();
        questao = new Questao();
    }

    public void remover(ActionEvent actionEvent) {
        factoryDAO.getInstance(daoClass).remove(questao.getIdQuestao());
        questoes = factoryDAO.getInstance(daoClass).findAll();
        questoesAtivas = factoryDAO.getInstance(daoClass).findQuestoesAtivas();
        questao = new Questao();
    }

    public void onRowEdit(RowEditEvent event) {
        Questao obj = (Questao) event.getObject();
        setQuestao(obj);
        gravar(null);
        FacesMessage msg = new FacesMessage("Editado", obj.getIdQuestao().toString());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public void onRowCancel(RowEditEvent<Questao> event) {
        FacesMessage msg = new FacesMessage("Cancelado", event.getObject().getIdQuestao().toString());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public Questao getQuestao() {
        return questao;
    }

    public void setQuestao(Questao questao) {
        this.questao = questao;
    }

    public List<Questao> getQuestoes() {
        return questoes;
    }

    public void setQuestoes(List<Questao> questoes) {
        this.questoes = questoes;
    }

    public List<Questao> getQuestoesAtivas() {
        return questoesAtivas;
    }

    public void setQuestoesAtivas(List<Questao> questoesAtivas) {
        this.questoesAtivas = questoesAtivas;
    }

}

src/main/webapp/prova.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                    template="./WEB-INF/Template.xhtml"
                    xmlns:p="http://primefaces.org/ui"
                    xmlns:h="http://xmlns.jcp.org/jsf/html"
                    xmlns:f="http://xmlns.jcp.org/jsf/core">
        <ui:define name="content">
            <br/>
            <h2>Provas</h2>
            <br/>
            <h:form id="form">
                <p:growl id="msgs" showDetail="true"/>
                <p:dataTable var="valor" value="#{provaController.provas}"
                             id="tabela" emptyMessage="Nenhum registro encontrado"
                             paginatorTemplate="{RowsPerPageDropdown} {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                             paginator="true" rows="10" rowsPerPageTemplate="5,10,25,50,100,9999" editable="true">

                    <p:ajax event="rowEdit" listener="#{provaController.onRowEdit}" update=":form:msgs" />
                    <p:ajax event="rowEditCancel" listener="#{provaController.onRowCancel}" update=":form:msgs" />

                    <p:column headerText="Código" sortBy="#{valor.idProva}" filterBy="#{valor.idProva}">
                        <h:outputText value="#{valor.idProva}" />
                    </p:column>

                    <p:column headerText="Data" sortBy="#{valor.dataFormatada}" filterBy="#{valor.dataFormatada}">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{valor.dataFormatada}" /></f:facet>
                            <f:facet name="input"><p:datePicker value="#{valor.dataProva}" style="width:100%"/></f:facet>
                        </p:cellEditor>
                    </p:column>

                    <p:column headerText="Questões" sortBy="#{valor.questaoList}" filterBy="#{valor.questaoList}">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{valor.questaoList}" /></f:facet>
                            <f:facet name="input">
                                <p:selectCheckboxMenu id="multiple" value="#{valor.questaoList}" label="Questões" style="width:100%"
                                                      multiple="true" filter="true" filterMatchMode="startsWith" panelStyle="width: 30rem" scrollHeight="250">
                                    <f:selectItems value="#{questaoController.questoesAtivas}"/>
                                </p:selectCheckboxMenu>
                            </f:facet>
                        </p:cellEditor>
                    </p:column>

                    <p:column headerText="Opções" exportable="false">
                        <p:rowEditor id="edit"/>

                        <p:commandLink value="Deletar" onclick="PF('remove').show();" class="ui-icon ui-icon-trash"> 
                            <f:setPropertyActionListener target="#{provaController.prova}"
                                                         value="#{valor}" />
                        </p:commandLink> 
                    </p:column>
                </p:dataTable>
            </h:form>

            <br/>

            <h:form>
                <p:commandButton icon="ui-icon-plus" value="Novo" onclick="PF('record').show();" />  
            </h:form>
            
            <h:form>
                <div align="center">
                    <h3>Exportar dados da página</h3>

                    <h:commandLink id="excel">
                        <p:graphicImage name="imagens/exports/excel.png" />
                        <p:dataExporter type="xls" target=":form:tabela" fileName="export"/>
                    </h:commandLink>

                    <h:commandLink id="xlsx">
                        <p:graphicImage name="imagens/exports/excelN.png" width="2%" />
                        <p:dataExporter type="xlsxstream" target=":form:tabela" fileName="export"/>
                    </h:commandLink>

                    <h:commandLink id="pdf">
                        <p:graphicImage name="imagens/exports/pdf.png" />
                        <p:dataExporter type="pdf" target=":form:tabela" fileName="export" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage name="imagens/exports/csv.png" width="24"/>
                        <p:dataExporter type="csv" target=":form:tabela" fileName="export" />
                    </h:commandLink>

                    <h:commandLink>
                        <p:graphicImage  name="imagens/exports/xml.png" width="24"/>
                        <p:dataExporter type="xml" target=":form:tabela" fileName="export" />
                    </h:commandLink>
                </div>
            </h:form>

            <p:dialog header="Novo" widgetVar="record" modal="true">
                <h:form>
                    <p:panelGrid id="panelRecord" columns="2">
                        Data:
                        <p:datePicker value="#{provaController.prova.dataProva}" style="width: 100%" />
                        Questões:
                        <p:selectCheckboxMenu id="multiple" value="#{provaController.prova.questaoList}" label="Questões" style="width: 99%"
                                              multiple="true" filter="true" filterMatchMode="startsWith" panelStyle="width: 30rem" scrollHeight="250">
                            <f:selectItems value="#{questaoController.questoesAtivas}"/>
                        </p:selectCheckboxMenu>
                    </p:panelGrid>
                    <br/>
                    <p:commandButton value="Salvar"  
                                     actionListener="#{provaController.gravar}" onclick="record.hide()" alt="Record"/> 
                </h:form>
            </p:dialog>

            <p:dialog header="Delete" widgetVar="remove" modal="true"> 
                <h:form>
                    Você tem certeza?
                    <p:commandButton value="Deletar"  
                                     actionListener="#{provaController.remover}" onclick="remove.hide()" alt="Delete" /> 
                </h:form>
            </p:dialog>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/realizarProva.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                    template="./WEB-INF/Template.xhtml"
                    xmlns:p="http://primefaces.org/ui"
                    xmlns:h="http://xmlns.jcp.org/jsf/html"
                    xmlns:f="http://xmlns.jcp.org/jsf/core">
        <ui:define name="content">
            <div style="margin: 0 auto; max-width: 930px">
                <br />
                <c:if test='#{realizarProvaController.prova == null}'>
                    <h1 style="text-align: center">Nenhuma nova prova marcada ainda!</h1>
                </c:if>
                <c:if test='#{realizarProvaController.prova != null}'>
                    <h1>Prova de ${realizarProvaController.prova.dataFormatada}. Valor 10 pontos.</h1>
                    <p:outputLabel value="Confira todas as respostas antes de enviar, e clique no botão 'Enviar prova'" />
                    <h:form>
                        <c:forEach items="${realizarProvaController.prova.questaoList}" var="questao" varStatus="loop">
                            <h:panelGrid>
                                <h3 style="margin-bottom: 0"> ${loop.index + 1}) #{questao.descricaoQuestao}</h3>

                                <c:if test='#{questao.tipoQuestaoidTipoQuestao.nomeTipoQuestao eq "Discursiva"}'>
                                    <p:inputTextarea rows="5" cols="100" value="#{questao.resposta}" />
                                </c:if>

                                <c:if test='#{questao.tipoQuestaoidTipoQuestao.nomeTipoQuestao eq "Múltipla escolha"}'>
                                    <p:selectOneRadio layout="grid" columns="1" value="#{questao.resposta}">
                                        <f:selectItem itemLabel="a)#{questao.alternativaA}" itemValue="A" />
                                        <f:selectItem itemLabel="b)#{questao.alternativaB}" itemValue="B" />
                                        <f:selectItem itemLabel="c)#{questao.alternativaC}" itemValue="C" />
                                        <f:selectItem itemLabel="d)#{questao.alternativaD}" itemValue="D" />
                                        <f:selectItem itemLabel="e)#{questao.alternativaE}" itemValue="E" />
                                    </p:selectOneRadio>
                                </c:if>
                            </h:panelGrid>
                        </c:forEach>

                        <br />
                        <p:commandButton value="Enviar prova" style="float: right" onclick="PF('finalizar').show();" /> 
                        <br />
                        <br />
                    </h:form>
                </c:if>
            </div>

            <p:dialog header="Atenção" widgetVar="finalizar" modal="true"> 
                <h:form>
                    <p>Finalizar Prova?</p>
                    <p:commandButton value="Confirmar" action="#{realizarProvaController.finalizarProva()}" style="float: right" /> 
                </h:form>
            </p:dialog>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/resultados.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                    template="./WEB-INF/Template.xhtml"
                    xmlns:p="http://primefaces.org/ui"
                    xmlns:h="http://xmlns.jcp.org/jsf/html">
        <ui:define name="content">
            <div style="margin: 0 auto; max-width: 930px">
                <br />
                <c:if test='#{resultadoController.resultados.size() eq 0}'>
                    <h1 style="text-align: center">Nenhuma prova encontrada</h1>
                </c:if>
                <c:if test='#{resultadoController.resultados.size() > 0}'>
                    <h1 style="text-align: center">Resultados das suas provas feitas:</h1>
                    <c:forEach items="${resultadoController.resultados}" var="resultado" varStatus="loop">
                        <h3>
                            Prova do dia ${resultado.provaidProva.dataFormatada}
                            <c:if test='#{loop.index eq 0}'>
                                (Última prova respondida)
                            </c:if>
                        </h3>
                        <li>Nota: #{resultado.valorObtido}</li>
                        <br />
                    </c:forEach>
                </c:if>
            </div>
        </ui:define>
    </ui:composition>
</html>